language: node_js
env:
  global:
  - CXX=g++-4.8
node_js:
- node
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
script:
- npm run build
before_deploy:
- tar -czvf corkboardFrontend.tar.gz -C dist .
deploy:
  - provider: s3
    access_key_id: AKIAI6J3DLDG65WB423Q
    secret_access_key:
      secure: oZ6mrwnbMjf5EjAMZDgy5xJTPECKEGpzmRIGzXn0KruCn/ls1C1vR4AWEvO5P82e7jHEOcSAYja7bFOGTMKD8SRx1h+wpYUDTtjdMIMQecURdNG2NDDI4x6j71aypVviZEqdzFxGi8MJkc9d+dfTXRLjxRPsWjsOheyMyPFH/1OXEpm9Q8The8zlRhdR6VrRaBrssGhJO9HDDVDjJd66XDutM7GHHXNmeGTsWlGg5vDlu3wwe4+WrLXVOZH5KQzKf4gtjjLqq5E2yODLtFXNqt4TDT/kpdtNG8BGxbsnIo6HWizUZpQS+wDXbZY4X8PBktkKP+cJJWEkYvrlOxL5Dw8UNlXbAbWe2ffIfro2VdXkQZu3pIeLXyD9gO8q3MIDfEEHwnrH+Vzb4/vivWXgvmKEu2qQyX+wn97pPp/KuKflP/r7xn+ZLWzUFDoubwhVTq5ZG60a31y24301cDVm2uJHJwBgBA5PUs1OfC53hc8AC9Dt8CaA8OIUUc2JHkMHaH/tWqye3rF/zmcReNQbYHdmIWxTx7GjSDPYftljVAfirSuQya6pygRQfur0hl1cPNvuf3VhdVOx4l9UXYCILfGzovlIOClaaTHrR8DNP9qgBy7SJuHZn6vSsG/mtB+S0mwzbBpwnhkGwFrk1G/KU4/XlD9/qhTc/l+bMP/gQQI=
    bucket: corkboard.t.ac.st
    skip_cleanup: true
    local_dir: dist
    acl: public_read
    on:
      repo: acstech/corkboard-sample
      branch: master
      tags: true
  - provider: releases
    api_key:
      secure: VBPwOCxn+nW1y06K/Zn9KTJGGGXedpstttrCh/9eg0rHMgV/K/piZuWwiYBp65pcP18Nv+qwc1Aj3lLhg4TI/sVmTH1OjpgNs8GuVEy5Q5VY8epjxZvdLZUO7i94nGCqygUBIYXWyyH7YbczuN4UtZifoXQjsMznj1N0M6pazJzG/42F+9wQpKHq76pHGG4EB+gqVM7xSa932bZ+Tt0cl66E4ubcU41xzg77WCuinoPwhu/ivDDUJcX06CnePN8zlXVTAJBB0Cq3AzxLFsFlFNavkNrccLI6Id3DZZIyaragqTDG3Arfsmto+Czj/AYSm6b6b3HxNlekoIxvjfhiLbzJswiX1K79RrlxGCW3oN2ob2f2VMN6EhNCaHmRJOBgXbnaQ/c13bpWifjkC3f81t/2T1la7UnMh+bqdbEIpgz6HaFkybcem+kPs8QY9Z1vsWrAdrt2Z9aaGYhXC+8KfhHHw367P5VknBDJl8SkxDo5SD6eTi97zb0pDVG7Ga/9K/9XrqhCSJB3bGsDW002DPxCjasz9n+DtEyhT+Zo89kKHBKzrAmGfHNmKEeAL21jxmUyo8+pkhDuVAgGO7jhsMQxemyVIIFDlBJfyfxHcLE9lqeIneXXQH3LIjl3JHA+CSAaCzpYwPymy1kRPgQEw70DsR0iYqu3Tw+z8aLE4Rk=
    file: corkboardFrontend.tar.gz
    skip_cleanup: true
    on:
      repo: acstech/corkboard-sample
      tags: true
